# Generated by Django 2.2.2 on 2020-03-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llamadasentrantes',
            old_name='archivo',
            new_name='id_archivo',
        ),
    ]
